### ISSUE TITLE
Which results to adopt?

### ISSUE THREAD

**Issue by Ewanwong** [mohsenfayyaz/DecompX#2]
Hi,
I've browsed your paper and codebase and find it very interesting! One tiny question is that in the demo you have several different attribution results, e.g., importance last/all layer aggregated/pooler/classifier, I wonder which one should I adopt if I want to explain a sequence classification model's prediction? Thank you so much!

**Comment by mohsenfayyaz** [comment]
Hi, 
Thank you for your question and for your interest in our work! For explaining a sequence classification model's predictions, we recommend using the `importance_last_layer_classifier` output, which has the shape `(batch, seq_len, classes)`. This is the final product of DecompX and provides the importance of each token (seq_len) for each output class (classes).

You can also explore visualizations of these attributions in our Colab demo: [DecompX Colab Demo](https://github.com/mohsenfayyaz/DecompX/blob/main/DecompX_Colab_Demo.ipynb).

We hope this helps! Let us know if you have further questions.

**Comment by Ewanwong** [comment]
Thank you so much for the clarification. It helps a lot!
